name: small
type: ddit
hidden_size: 768
cond_dim: 128
length: 16
n_blocks: 12
n_heads: 12
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: True
adaln: False
#attn_backend: flash_attn
attn_backend: sdpa
time_vocab_size: 256

vocab_size: 8264        # 路段 token 上限 + 1( PAD )


max_path_id: 8263